# Generated by Django 4.2.1 on 2023-06-19 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sgu', '0003_alumno_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgl.leccion')),
            ],
        ),
        migrations.CreateModel(
            name='progresoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccionCompleta', models.BooleanField(default=False)),
                ('ejercicioCompleto', models.BooleanField(default=False)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgu.alumno')),
                ('idEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgl.ejercicio')),
                ('idLeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgl.leccion')),
            ],
            options={
                'unique_together': {('idAlumno', 'idLeccion', 'idEjercicio')},
            },
        ),
    ]
