# Generated by Django 4.2.1 on 2023-06-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.TextField()),
                ('es_correcta', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='progresoejercicios',
            name='idEjercicio',
        ),
        migrations.RemoveField(
            model_name='progresolecciones',
            name='idLeccion',
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.DeleteModel(
            name='Leccion',
        ),
        migrations.DeleteModel(
            name='progresoEjercicios',
        ),
        migrations.DeleteModel(
            name='progresoLecciones',
        ),
        migrations.AddField(
            model_name='opcion',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgl.pregunta'),
        ),
    ]
