# Generated by Django 4.2.1 on 2023-06-19 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0003_alumno_edad'),
        ('sgl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='progresoEjercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicioCompleto', models.BooleanField(default=False)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgu.alumno')),
                ('idEjercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgl.ejercicio')),
            ],
            options={
                'unique_together': {('idAlumno', 'idEjercicio')},
            },
        ),
        migrations.CreateModel(
            name='progresoLecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leccionCompleta', models.BooleanField(default=False)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgu.alumno')),
                ('idLeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgl.leccion')),
            ],
            options={
                'unique_together': {('idAlumno', 'idLeccion')},
            },
        ),
        migrations.DeleteModel(
            name='progresoGlobal',
        ),
    ]
