# Generated by Django 4.2.1 on 2023-06-24 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0003_respuestausuario_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='examen',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sgl.examen'),
            preserve_default=False,
        ),
    ]
