# Generated by Django 4.2.1 on 2023-06-24 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0004_examen_pregunta_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sgl.examen'),
            preserve_default=False,
        ),
    ]
