# Generated by Django 4.2.1 on 2023-06-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgl', '0005_calificacion_examen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Examen',
            new_name='Leccion',
        ),
    ]
