# Generated by Django 4.2.1 on 2023-06-19 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='idCuidador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sgu.cuidador'),
        ),
    ]
