# Generated by Django 4.2.1 on 2023-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0002_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
