# Generated by Django 4.2.1 on 2023-06-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0002_padre_profesor_salud_delete_parent_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='numero_telefono',
            field=models.CharField(max_length=100),
        ),
    ]
