# Generated by Django 4.2.1 on 2023-06-19 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0002_alumno_idcuidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='edad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El valor debe ser igual o mayor a 0.'), django.core.validators.MaxValueValidator(150, message='El valor debe ser igual o menor a 150.')]),
            preserve_default=False,
        ),
    ]
