# Generated by Django 4.2.1 on 2023-06-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0004_padre_usuario_profesor_usuario_salud_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padre',
            old_name='phoneNumber',
            new_name='numero_telefono',
        ),
        migrations.AddField(
            model_name='profesor',
            name='delegacion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salud',
            name='delegacion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
