# Generated by Django 4.2.1 on 2023-06-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0004_usuario_remove_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno_cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sgu.alumno')),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgu.cuidador')),
            ],
        ),
    ]
