# Generated by Django 4.2.1 on 2023-06-19 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0005_alumno_cuidador'),
    ]

    operations = [
        migrations.CreateModel(
            name='padre',
            fields=[
                ('cuidador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sgu.cuidador')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('delegacion', models.CharField(max_length=100)),
            ],
            bases=('sgu.cuidador',),
        ),
        migrations.CreateModel(
            name='profesor',
            fields=[
                ('cuidador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sgu.cuidador')),
                ('cedula', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('delegacion', models.CharField(max_length=100)),
            ],
            bases=('sgu.cuidador',),
        ),
        migrations.CreateModel(
            name='salud',
            fields=[
                ('cuidador_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sgu.cuidador')),
                ('cedula', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('delegacion', models.CharField(max_length=100)),
            ],
            bases=('sgu.cuidador',),
        ),
    ]
