# Generated by Django 4.2.1 on 2023-06-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0007_user_teacher_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apellido',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='password2',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
