# Generated by Django 4.2.1 on 2023-06-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0008_rename_apellido_user_password1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='initUser',
        ),
    ]
