# Generated by Django 4.2.1 on 2023-06-25 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgu', '0009_alumno_diagnostico_alumno_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='diagnostico',
        ),
    ]
